### ISSUE TITLE
Add guide for Bedrock edition

### ISSUE THREAD

**Issue by misterquestions** [Love-and-Tolerance/Resource-Pack-Guide#4]
Hey,

The guide you guys created for Java Edition is just awesome and really clear, I'd be awesome if you can create one for Bedrock Edition as well since there are differences that may be difficult to understand for others (for example me lol)

Thanks.

**Comment by SilkRose** [comment]
I am currently working on converting the guide into a website, after this is done we are planning on making a Bedrock guide.
